// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:web:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    authDomain: 'tobi-to-do.firebaseapp.com',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOOdwAiLRdtYNONL3kNcafz07Hte_N7jg',
    appId: '1:730780218273:android:9b86d8d1eedb2be9d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp1MrfCIAv0DWisUV6VKyP6V531oWAin8',
    appId: '1:730780218273:ios:3bfbd40138bf89abd9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
    iosClientId: '730780218273-jvhhhh82g5br9biqpiscdeks227ho1hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp1MrfCIAv0DWisUV6VKyP6V531oWAin8',
    appId: '1:730780218273:ios:3bfbd40138bf89abd9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
    iosClientId: '730780218273-jvhhhh82g5br9biqpiscdeks227ho1hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:web:08038d45fbdb5590d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    authDomain: 'tobi-to-do.firebaseapp.com',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );
}
