// File generated by flutterfire_cli.
// See https://github.com/firebase/flutterfire_cli for more information.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:web:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    authDomain: 'tobi-to-do.firebaseapp.com',
    storageBucket: 'tobi-to-do.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:android:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:ios:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
    iosBundleId: 'com.example.tobiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:macos:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:windows:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAYkZHimR12SSGnSKxy3lUHybSgFB5VZX0',
    appId: '1:730780218273:linux:a58712579f85c569d9d1e0',
    messagingSenderId: '730780218273',
    projectId: 'tobi-to-do',
    storageBucket: 'tobi-to-do.firebasestorage.app',
  );
}
